version: '3'

services:
#1 mongodb and postgressdb run parallel
  mongodb:
    image: mongo
    ports:
    - 27017:27017

#1 mongodb and postgressdb run parallel
  postgresdb:
    image: postgres:11.2-alpine
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=postgres_db
    
#2
  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/tweets
    depends_on:
    - mongodb

#3
  etl:
    build: etl/
    volumes:
    - ./etl/:/etl
    depends_on:
    - postgresdb
    - mongodb

